export const payloadSamples = [
  { name: 'Recycle Bin Cleaner', category: 'Maintenance', size: '22kb', nodes: ['on_launch', 'send_report'], payload: { action: 'clean_recycle_bin', targets: ['%RECYCLEBIN%', '~/.Trash'] } },
  { name: 'Temp File Purger', category: 'Maintenance', size: '18kb', nodes: ['on_launch', 'send_report'], payload: { action: 'purge_temp', paths: ['%TEMP%', '/tmp'], older_than_days: 7 } },
  { name: 'Log Rotator', category: 'Maintenance', size: '12kb', nodes: ['on_launch'], payload: { action: 'rotate_logs', compress: true, older_than_days: 30 } },
  { name: 'Disk Space Monitor', category: 'Maintenance', size: '9kb', nodes: ['on_launch', 'send_report'], payload: { action: 'disk_monitor', threshold_pct: 85 } },
  { name: 'Certificate Expiry Checker', category: 'Maintenance', size: '18kb', nodes: ['local_intel_match'], payload: { action: 'scan_cert_expiry', threshold_days: 30 } },
  { name: 'Stale Process Killer', category: 'Maintenance', size: '11kb', nodes: ['process_watch', 'kill_process'], payload: { action: 'kill_stale_procs', older_than_hours: 24, name_pattern: '' } },
  { name: 'Registry Patcher', category: 'Security', size: '17kb', nodes: ['registry_watch', 'send_report'], payload: { action: 'registry_patch', hive: 'HKLM', key: '', expected_value: '', patch_value: '' } },
  { name: 'Driver Integrity Checker', category: 'Security', size: '24kb', nodes: ['local_intel_match', 'send_report'], payload: { action: 'driver_integrity', hash_allowlist: [] } },
  { name: 'Known-Bad Hash Scanner', category: 'Security', size: '31kb', nodes: ['port_scan', 'send_report'], payload: { action: 'hash_scan', scan_paths: [], blocklist: [] } },
  { name: 'Hosts File Monitor', category: 'Security', size: '8kb', nodes: ['file_integrity_check', 'send_report'], payload: { action: 'hosts_monitor', path: '/etc/hosts' } },
  { name: 'Firewall Rule Auditor', category: 'Security', size: '19kb', nodes: ['on_launch', 'send_report'], payload: { action: 'fw_audit', flag_unexpected_inbound: true } },
  { name: 'Scheduled Task Auditor', category: 'Security', size: '15kb', nodes: ['on_launch', 'send_report'], payload: { action: 'task_audit', flag_unknown_executables: true } },
  { name: 'SSH Auth Log Scanner', category: 'Security', size: '13kb', nodes: ['log_tail', 'send_report'], payload: { action: 'ssh_log_scan', path: '/var/log/auth.log', flag_failed_attempts: 5 } },
  { name: 'Sudoers Integrity', category: 'Security', size: '10kb', nodes: ['file_integrity_check'], payload: { action: 'sudoers_check', path: '/etc/sudoers' } },
  { name: 'Service Fingerprinter', category: 'Intelligence', size: '16kb', nodes: ['banner_grab', 'send_report'], payload: { action: 'fingerprint_services', ports: [22, 80, 443, 3306, 5432] } },
  { name: 'Network Change Detector', category: 'Intelligence', size: '14kb', nodes: ['peer_sync', 'write_deadrop'], payload: { action: 'arp_diff', interface: 'eth0' } },
  { name: 'Port Listener', category: 'Intelligence', size: '9kb', nodes: ['deploy_honeypot'], payload: { action: 'passive_listen', port: 4444, log_payloads: true } },
  { name: 'DNS Anomaly Detector', category: 'Intelligence', size: '12kb', nodes: ['dns_resolve', 'send_report'], payload: { action: 'dns_baseline_diff', domains: [], flag_new_records: true } },
  { name: 'Open Port Mapper', category: 'Recon', size: '13kb', nodes: ['port_scan', 'banner_grab'], payload: { action: 'tcp_connect_scan', port_range: '1-1024' } },
  { name: 'HTTP Endpoint Crawler', category: 'Recon', size: '20kb', nodes: ['http_probe', 'send_report'], payload: { action: 'http_crawl', paths: ['/', '/api', '/admin', '/health'], follow_redirects: false } },
  { name: 'TLS Cert Inventory', category: 'Recon', size: '11kb', nodes: ['tls_check', 'send_report'], payload: { action: 'tls_inventory', ports: [443, 8443] } },
];
